### ISSUE TITLE
Breaking change in protobuf dependancy that causes a crash.

### ISSUE THREAD

**Issue by snaeji** [terrabythia/dart_chromecast#14]
There is a breaking change in the protobuf plugin that dart_chromecast depends on.

Latest version supported is protobuf: 0.13.16+1

[https://github.com/dart-lang/protobuf/issues/284](https://github.com/dart-lang/protobuf/issues/284)

**Comment by terrabythia** [comment]
Thanks for reporting this error! I've fixed this in my latest commit (version tag 0.1.2).
