### ISSUE TITLE
Screenshare ?

### ISSUE THREAD

**Issue by winwisely99** [terrabythia/dart_chromecast#15]
Can I screenshare an app from the mobile to the Chromecast with this ?

You only mention casting videos in the readme 

Thanks !

**Comment by gdelataillade** [comment]
> Can I screenshare an app from the mobile to the Chromecast with this ?
> 
> You only mention casting videos in the readme
> 
> Thanks !

Did you found something?

**Comment by terrabythia** [comment]
This library is only made for casting video files (right now). You could try feeding it a stream url, but that probably won't work.
