### ISSUE TITLE
Invalid argument(s): "<" expected at 1:1

### ISSUE THREAD

**Issue by holyspidoo** [terrabythia/dart_chromecast#2]
Trying to use this library but having an issue when trying to get a CastDevice

```
CastDevice device = CastDevice(name:info.name,host: info.address,port:info.port,type: '_googlecast._tcp');
```
This gives me the error:
```
Invalid argument(s): "<" expected at 1:1
#0      parse (package:xml/xml.dart:43:5)
#1      new CastDevice.<anonymous closure> (package:dart_chromecast/casting/cast_device.dart:33:36)
#2      _RootZone.runUnary (dart:async/zone.dart:1379:54)
#3      _FutureListener.handleValue (dart:async/future_impl.dart:129:18)
#4      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:642:45)
#5      Future._propagateToListeners (dart:async/future_impl.dart:671:32)
#6      Future._complete (dart:async/future_impl.dart:476:7)
#7      _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#8      _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#9      _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:295:13)
#10     _withClient (package:http/http.dart)
<asynchronous suspension>
#11     get (package:http/http.dart:46:5)
```

Any ideas?

**Comment by NBTX** [comment]
In order to get information about your device, the library makes an HTTP GET request to `http://${host}:8008/ssdp/device-desc.xml`. The result you're getting is an invalid response.

I recommend printing `info.address` and then making the GET request in your browser, substituting the printed address into the above URL. If you still can't determine the cause of the issue, I recommend you post the response here.

**Comment by holyspidoo** [comment]
From the browser, I can easily get info from /setup/eureka_info but never from /ssdp/device-desc.xml

**Comment by terrabythia** [comment]
Didn't know about the eureka_info way to get the device's info. Seems to be a better fit for this use case, since it's JSON and not (annoying) XML and we can also specify which params we would like to have returned.

Updated the code to use eureka_info instead of device_info.

**Comment by holyspidoo** [comment]
For model name and friendly name, there is no need for eureka_info since we already have the attributes bundle to decode? You can look at how I did it in:
[cast_device](https://github.com/holyspidoo/dart_chromecast/blob/master/lib/casting/cast_device.dart)
