### ISSUE TITLE
Make dart_chromecast depend on xml ^4.1.0

### ISSUE THREAD

**Issue by snorreks** [terrabythia/dart_chromecast#20]
I cannot run flutter, since the old flutter_svg package (v 0.17) produces errors on the newest version of flutter: 1.20.1.
But I can't upgrade the package to 0.18, since it requires xml ^4.1.0, and dart_chromecast 0.1.2 depends on xml ^3.0.0 and it is not possible to use the xml ^4.1.0 because of this.

Is it possible for me to manually override what this package depends on?

**Comment by snorreks** [comment]
A temporary fix is to override dependencies:
` 
dependency_overrides:
  xml: 4.1.0
`

**Comment by terrabythia** [comment]
You are always welcome to fork this project, make the changes yourself and then do a pull request! :) 

I've updated the xml package to 4.1.0
