### ISSUE TITLE
OS Error:  WRONG_VERSION_NUMBER(tls_record.cc:242)

### ISSUE THREAD

**Issue by Gursewak-Uppal** [terrabythia/dart_chromecast#21]
I tried to cast screen using this plugin but it give me error.
class CastSender and method _createSocket() 
OS Error:  WRONG_VERSION_NUMBER(tls_record.cc:242)

**Comment by terrabythia** [comment]
I have seen the error 'WRONG_VERSION_ NUMBER' before, but I just tested my package again and had no problems.

Which version ChromeCast do you have?

**Comment by Gursewak-Uppal** [comment]
dart_chromecast 0.2.1

**Comment by terrabythia** [comment]
I thought you might have an old Chromecast (the Chromecast itself, not this library), but I've just tested it with a first generation Chromecast and everything is working fine. I'm really not sure what is causing your problems, but maybe you could try building the app on another device?

**Comment by terrabythia** [comment]
Closing this because the issue is not reproducable (and due to inactivity).
