### ISSUE TITLE
"reusePort not supported" error when running example, or similar find_chromecasts() call, on Windows/Android

### ISSUE THREAD

**Issue by waded** [terrabythia/dart_chromecast#25]
When attempting to run the provided index.dart on Dart version 2.10.2 on Windows*, I get an exception:

Command: 
`dart example/index.dart http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4`

Result:
```
Looking for ChromeCast devices...
Dart Socket ERROR: ../../third_party/dart/runtime/bin/socket_win.cc:194: `reusePort` not supported for Windows.Dart Socket ERROR: ../../third_party/dart/runtime/bin/socket_win.cc:194: `reusePort` not supported for Windows.Unhandled exception:
SocketException: Failed to create datagram socket (OS Error: The requested address is not valid in its context.
, errno = 10049), address = , port = 5353
#0      _NativeSocket.bindDatagram (dart:io-patch/socket_patch.dart:798:7)
<asynchronous suspension>
#1      _RawDatagramSocket.bind (dart:io-patch/socket_patch.dart:2155:26)
#2      RawDatagramSocket.bind (dart:io-patch/socket_patch.dart:2113:31)
#3      MDnsClient.start (package:multicast_dns/multicast_dns.dart:127:71)
<asynchronous suspension>
#4      find_chromecasts (package:dart_chromecast/utils/mdns_find_chromecast.dart:19:16)
...
```

(* current latest provided with Flutter SDK. I'm not making an Android/iOS app in this case, just REPLing with dart_chromecast. I'm curious if I'd hit a similar issue on Android, though.)

**Comment by waded** [comment]
FWIW, the example does work if you forgo MDNS discovery by using `--host`, e,g:

`dart example/index.dart http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4 --host 192.168.86.26`

**Comment by waded** [comment]
Satisfying curiosity mentioned earlier, code similar to the example does not work on Android either. e.g.

`List<find_chromecast.CastDevice> devices = await find_chromecast.find_chromecasts();`

in a Flutter app results in:

`E/Dart    (20025): Dart Socket ERROR: ../../third_party/dart/runtime/bin/socket_android.cc:147: `reusePort` not supported for Android.`

Updating title to incl. Android.

**Comment by peterscodee** [comment]
This appears to be a problem of the [multicast_dns](https://pub.dev/packages/multicast_dns) plugin. You can find the corresponding issue here: [#55173](https://github.com/flutter/flutter/issues/55173)
