### ISSUE TITLE
iOS 14 issue

### ISSUE THREAD

**Issue by hateftad** [terrabythia/dart_chromecast#27]
Hi,
it doesnt seem to be working on iOS. Searching for devices returns no results

**Comment by snaeji** [comment]
You may have to add this in your `Info.plist` if you are having iOS14 problems.

```
<key>NSBonjourServices</key>
<array>
	<string>_googlecast._tcp</string>
	<string>"Receiver id"._googlecast._tcp</string>
</array>
```

**Comment by penniath** [comment]
Worked for me!

Thanks @snaeji!

**Comment by vipindhangar1107** [comment]
Worked me also.

Thanks @snaeji

**Comment by terrabythia** [comment]
Closing this because the solution seems to be working and actually is not related to this project directly (this is just dart code, nothing to do with iOS).
