### ISSUE TITLE
Null safety

### ISSUE THREAD

**Issue by peterscodee** [terrabythia/dart_chromecast#35]
This is a request to add support for null safety to this package.
See the [migration guide](https://dart.dev/null-safety/migration-guide) for details about enabling null safety.

**Comment by dgilperez** [comment]
+1 on this one. This is preventing us to upgrade

**Comment by terrabythia** [comment]
Merged your branch into this project and fixed the problems (like using a Flutter library). 

Newest version now supports null safety, so I will close this issue.
