### ISSUE TITLE
Fix pub analysis error

### ISSUE THREAD

**Issue by peterscodee** [terrabythia/dart_chromecast#37]
Since Dart 1.12 `dart_chromecast` does not pass static analysis on [pub.dev](https://www.pub.dev). 
This also applies to packages depending on this library and thus is crucial to me.

![Capture](https://user-images.githubusercontent.com/46222898/114272023-94b75b80-9a14-11eb-8eff-a30bc4443704.PNG)

**Comment by peterscodee** [comment]
The reason for this is that `dart_chromcast` depends on `observable ^0.22.2` which depends on `dart_internal` which requires the dart version to be <2.12

**Comment by terrabythia** [comment]
Should be fixed because the current version does not depend on the `observable` package anymore.
