### ISSUE TITLE
Lets improve the package score

### ISSUE THREAD

**Issue by guyluz11** [terrabythia/dart_chromecast#46]
We getting fewer points on basic staff that we can easily improve.

For example to get the `static analysis` points we just need to run `dart format .`.

In the `Provide documentation` section we missing the example section which [exists](https://github.com/terrabythia/dart_chromecast/blob/master/example/index.dart) and we just need to show it correctly for [pub.dev](https://pub.dev).
And there are more.

![image](https://user-images.githubusercontent.com/9304740/131358332-a10c482f-580f-4c59-bc11-c5308aee330f.png)

If needed I will be happy to try getting more points.

**Comment by guyluz11** [comment]
![image](https://user-images.githubusercontent.com/9304740/148646902-74c4f5e1-b98b-4a12-bb54-9c9ea7bdc711.png)

🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉

Maybe we can support multiple platforms as well by moving from dart.io to [universal_io](https://pub.dev/packages/universal_io), I don't need runtime js but maybe it can help others.
![image](https://user-images.githubusercontent.com/9304740/148647005-8ad1a514-435c-4dfe-b156-26800a51a8cf.png)

Would you like me to open an issue for that as well?

**Comment by terrabythia** [comment]
🎉  great!

Replaced `dart:io` package with `universal:io` package in version 0.3.2, so the "support multiple platforms" should score 20 now too.

**Comment by guyluz11** [comment]
Nice, closing this issue now.
