### ISSUE TITLE
how send request headers

### ISSUE THREAD

**Issue by linkkader** [terrabythia/dart_chromecast#51]
hi please is there anyway to send request headers like user agent or cookie ?

**Comment by terrabythia** [comment]
Not with this library and I'm not even sure if it's possible at all.
Why would you want to do this?

**Comment by linkkader** [comment]
@terrabythia 
https://www.anitube.site/aHR0cHM6Ly9oYW1idXJndWVyYXJ0ZXNhbmFsMTIzLmJsb2dzcG90LmNvbS8yMDIyLzAxLzhlNTNhZTZiNjA4ZDllMDIuaHRtbA==/0/bg.mp4 
this video link  will just redirect on home page without  this header
referer : https://www.anitube.site/

**Comment by terrabythia** [comment]
Okay, I don't think it's possible to send along a header. What you could (maybe) do is create a proxy server that adds the needed headers and sends the request along.
