### ISSUE TITLE
Opening web page or youtube video

### ISSUE THREAD

**Issue by guyluz11** [terrabythia/dart_chromecast#59]
The example is using a .mp4 video that can be found on a public URL.

Is there a way to open web pages or youtube videos by sending URLs?

**Comment by terrabythia** [comment]
No, that's not possible. I don't believe that's possible at all with a crhomecast, you can only send direct video or image links.

**Comment by guyluz11** [comment]
I think it is possible because I've managed to do that using this package in NodeRED https://flows.nodered.org/node/node-red-contrib-castv2 that is written in JavaScript

**Comment by terrabythia** [comment]
Interesting! Didn't know there was an "open YouTube receiver". Should be possible to implement the same principle in this library (since it's just sending specific messages to the chromecast), but somebody else would have to write that implementation and create a PR.

**Comment by guyluz11** [comment]
> Interesting! Didn't know there was an "open YouTube receiver". Should be possible to implement the same principle in this library (since it's just sending specific messages to the chromecast), but somebody else would have to write that implementation and create a PR.

Cool so let's keep this issue open, if me or somebody will have the time we can easily find an issue to contribute to or discuss about it more.
