### ISSUE TITLE
Error!

### ISSUE THREAD

**Issue by SwaXTech** [terrabythia/dart_chromecast#8]
Compiler message:
file:///C:/flutter/.pub-cache/git/dart_chromecast-7a9e5ab973a8e387b81923f8a4483a23a49f2b61/lib/proto/cast_channel.pb.dart:16:7: Error: The non-abstract class 'CastMessage' is missing implementations for these members:
 - GeneratedMessage.createEmptyInstance
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class CastMessage extends GeneratedMessage {
      ^^^^^^^^^^^
file:///C:/flutter/.pub-cache/hosted/pub.dartlang.org/protobuf-0.13.4/lib/src/protobuf/generated_message.dart:52:20: Context: 'GeneratedMessage.createEmptyInstance' is defined here.
  GeneratedMessage createEmptyInstance();
                   ^^^^^^^^^^^^^^^^^^^
file:///C:/flutter/.pub-cache/git/dart_chromecast-7a9e5ab973a8e387b81923f8a4483a23a49f2b61/lib/proto/cast_channel.pb.dart:85:7: Error: The non-abstract class '_ReadonlyCastMessage' is missing implementations for these members:
 - GeneratedMessage.createEmptyInstance
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class _ReadonlyCastMessage extends CastMessage with ReadonlyMessageMixin {}
      ^^^^^^^^^^^^^^^^^^^^
file:///C:/flutter/.pub-cache/hosted/pub.dartlang.org/protobuf-0.13.4/lib/src/protobuf/generated_message.dart:52:20: Context: 'GeneratedMessage.createEmptyInstance' is defined here.
  GeneratedMessage createEmptyInstance();
                   ^^^^^^^^^^^^^^^^^^^
file:///C:/flutter/.pub-cache/git/dart_chromecast-7a9e5ab973a8e387b81923f8a4483a23a49f2b61/lib/proto/cast_channel.pb.dart:87:7: Error: The non-abstract class 'AuthChallenge' is missing implementations for these members:
 - GeneratedMessage.createEmptyInstance
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class AuthChallenge extends GeneratedMessage {
      ^^^^^^^^^^^^^
file:///C:/flutter/.pub-cache/hosted/pub.dartlang.org/protobuf-0.13.4/lib/src/protobuf/generated_message.dart:52:20: Context: 'GeneratedMessage.createEmptyInstance' is defined here.
  GeneratedMessage createEmptyInstance();
                   ^^^^^^^^^^^^^^^^^^^
file:///C:/flutter/.pub-cache/git/dart_chromecast-7a9e5ab973a8e387b81923f8a4483a23a49f2b61/lib/proto/cast_channel.pb.dart:109:7: Error: The non-abstract class '_ReadonlyAuthChallenge' is missing implementations for these members:
 - GeneratedMessage.createEmptyInstance
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class _ReadonlyAuthChallenge extends AuthChallenge with ReadonlyMessageMixin {}
      ^^^^^^^^^^^^^^^^^^^^^^
file:///C:/flutter/.pub-cache/hosted/pub.dartlang.org/protobuf-0.13.4/lib/src/protobuf/generated_message.dart:52:20: Context: 'GeneratedMessage.createEmptyInstance' is defined here.
  GeneratedMessage createEmptyInstance();
                   ^^^^^^^^^^^^^^^^^^^
file:///C:/flutter/.pub-cache/git/dart_chromecast-7a9e5ab973a8e387b81923f8a4483a23a49f2b61/lib/proto/cast_channel.pb.dart:111:7: Error: The non-abstract class 'AuthResponse' is missing implementations for these members:
 - GeneratedMessage.createEmptyInstance
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class AuthResponse extends GeneratedMessage {
      ^^^^^^^^^^^^
file:///C:/flutter/.pub-cache/hosted/pub.dartlang.org/protobuf-0.13.4/lib/src/protobuf/generated_message.dart:52:20: Context: 'GeneratedMessage.createEmptyInstance' is defined here.
  GeneratedMessage createEmptyInstance();
                   ^^^^^^^^^^^^^^^^^^^
file:///C:/flutter/.pub-cache/git/dart_chromecast-7a9e5ab973a8e387b81923f8a4483a23a49f2b61/lib/proto/cast_channel.pb.dart:147:7: Error: The non-abstract class '_ReadonlyAuthResponse' is missing implementations for these members:
 - GeneratedMessage.createEmptyInstance
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class _ReadonlyAuthResponse extends AuthResponse with ReadonlyMessageMixin {}
      ^^^^^^^^^^^^^^^^^^^^^
file:///C:/flutter/.pub-cache/hosted/pub.dartlang.org/protobuf-0.13.4/lib/src/protobuf/generated_message.dart:52:20: Context: 'GeneratedMessage.createEmptyInstance' is defined here.
  GeneratedMessage createEmptyInstance();
                   ^^^^^^^^^^^^^^^^^^^
file:///C:/flutter/.pub-cache/git/dart_chromecast-7a9e5ab973a8e387b81923f8a4483a23a49f2b61/lib/proto/cast_channel.pb.dart:149:7: Error: The non-abstract class 'AuthError' is missing implementations for these members:
 - GeneratedMessage.createEmptyInstance
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class AuthError extends GeneratedMessage {
      ^^^^^^^^^
file:///C:/flutter/.pub-cache/hosted/pub.dartlang.org/protobuf-0.13.4/lib/src/protobuf/generated_message.dart:52:20: Context: 'GeneratedMessage.createEmptyInstance' is defined here.
  GeneratedMessage createEmptyInstance();
                   ^^^^^^^^^^^^^^^^^^^
file:///C:/flutter/.pub-cache/git/dart_chromecast-7a9e5ab973a8e387b81923f8a4483a23a49f2b61/lib/proto/cast_channel.pb.dart:176:7: Error: The non-abstract class '_ReadonlyAuthError' is missing implementations for these members:
 - GeneratedMessage.createEmptyInstance
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class _ReadonlyAuthError extends AuthError with ReadonlyMessageMixin {}
      ^^^^^^^^^^^^^^^^^^
file:///C:/flutter/.pub-cache/hosted/pub.dartlang.org/protobuf-0.13.4/lib/src/protobuf/generated_message.dart:52:20: Context: 'GeneratedMessage.createEmptyInstance' is defined here.
  GeneratedMessage createEmptyInstance();
                   ^^^^^^^^^^^^^^^^^^^
file:///C:/flutter/.pub-cache/git/dart_chromecast-7a9e5ab973a8e387b81923f8a4483a23a49f2b61/lib/proto/cast_channel.pb.dart:178:7: Error: The non-abstract class 'DeviceAuthMessage' is missing implementations for these members:
 - GeneratedMessage.createEmptyInstance
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class DeviceAuthMessage extends GeneratedMessage {
      ^^^^^^^^^^^^^^^^^
file:///C:/flutter/.pub-cache/hosted/pub.dartlang.org/protobuf-0.13.4/lib/src/protobuf/generated_message.dart:52:20: Context: 'GeneratedMessage.createEmptyInstance' is defined here.
  GeneratedMessage createEmptyInstance();
                   ^^^^^^^^^^^^^^^^^^^
file:///C:/flutter/.pub-cache/git/dart_chromecast-7a9e5ab973a8e387b81923f8a4483a23a49f2b61/lib/proto/cast_channel.pb.dart:217:7: Error: The non-abstract class '_ReadonlyDeviceAuthMessage' is missing implementations for these members:
 - GeneratedMessage.createEmptyInstance
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class _ReadonlyDeviceAuthMessage extends DeviceAuthMessage with ReadonlyMessageMixin {
      ^^^^^^^^^^^^^^^^^^^^^^^^^^
file:///C:/flutter/.pub-cache/hosted/pub.dartlang.org/protobuf-0.13.4/lib/src/protobuf/generated_message.dart:52:20: Context: 'GeneratedMessage.createEmptyInstance' is defined here.
  GeneratedMessage createEmptyInstance();
                   ^^^^^^^^^^^^^^^^^^^
Compiler terminated unexpectedly.

**Comment by terrabythia** [comment]
This should now be fixed.
